name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the sample program
        run: ./scripts/bz.py
        
      - name: Run the sample program
        run: ./bin/bzsample-linux_x64
        
  macos-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the sample program
        run: ./scripts/bz.py
        
      - name: Run the sample program
        run: ./bin/bzsample-mac_x64

  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the sample program
        run: python ./scripts/bz.py --verbose
        
      - name: Run the sample program
        run: bin\bzsample-win_x64
        shell: cmd
